spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: local
            client-secret: local
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
        provider:
          keycloak:
            authorization-uri: http://localhost/auth
            token-uri: http://localhost/token
            user-info-uri: http://localhost/userinfo
            jwk-set-uri: http://localhost/jwks
  datasource:
    url: jdbc:h2:mem:devdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false