server.port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: client1
            client-secret: I0zblmakBIXNJd1MLbFcDBHq5ALLemAs
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://100.72.130.7:8070/realms/realm1